package com.github.ksoichiro.androidcolorfulicons.demo;

import com.github.ksoichiro.androidcolorfulicons.R;

import java.util.ArrayList;

public class IconList extends ArrayList<Icon> {

    public IconList() {
        add(new Icon(R.drawable.ic_action_aci_comment, "ic_action_aci_comment"));
        add(new Icon(R.drawable.ic_action_aci_comment2, "ic_action_aci_comment2"));
        add(new Icon(R.drawable.ic_action_aci_comment3, "ic_action_aci_comment3"));
        add(new Icon(R.drawable.ic_action_aci_comment4, "ic_action_aci_comment4"));
        add(new Icon(R.drawable.ic_action_aci_settings, "ic_action_aci_settings"));
        add(new Icon(R.drawable.ic_action_aci_settings2, "ic_action_aci_settings2"));
        add(new Icon(R.drawable.ic_action_aci_settings3, "ic_action_aci_settings3"));
        add(new Icon(R.drawable.ic_action_aci_settings4, "ic_action_aci_settings4"));
        add(new Icon(R.drawable.ic_action_aci_settings5, "ic_action_aci_settings5"));
        add(new Icon(R.drawable.ic_action_aci_lock, "ic_action_aci_lock"));
        add(new Icon(R.drawable.ic_action_aci_unlock, "ic_action_aci_unlock"));
        add(new Icon(R.drawable.ic_action_aci_check, "ic_action_aci_check"));
        add(new Icon(R.drawable.ic_action_aci_check2, "ic_action_aci_check2"));
        add(new Icon(R.drawable.ic_action_aci_check3, "ic_action_aci_check3"));
        add(new Icon(R.drawable.ic_action_aci_box, "ic_action_aci_box"));
        add(new Icon(R.drawable.ic_action_aci_check4, "ic_action_aci_check4"));
        add(new Icon(R.drawable.ic_action_aci_check5, "ic_action_aci_check5"));
        add(new Icon(R.drawable.ic_action_aci_done, "ic_action_aci_done"));
        add(new Icon(R.drawable.ic_action_aci_finish, "ic_action_aci_finish"));
        add(new Icon(R.drawable.ic_action_aci_add, "ic_action_aci_add"));
        add(new Icon(R.drawable.ic_action_aci_plus, "ic_action_aci_plus"));
        add(new Icon(R.drawable.ic_action_aci_plus2, "ic_action_aci_plus2"));
        add(new Icon(R.drawable.ic_action_aci_minus, "ic_action_aci_minus"));
        add(new Icon(R.drawable.ic_action_aci_minus2, "ic_action_aci_minus2"));
        add(new Icon(R.drawable.ic_action_aci_info, "ic_action_aci_info"));
        add(new Icon(R.drawable.ic_action_aci_info2, "ic_action_aci_info2"));
        add(new Icon(R.drawable.ic_action_aci_help, "ic_action_aci_help"));
        add(new Icon(R.drawable.ic_action_aci_help2, "ic_action_aci_help2"));
        add(new Icon(R.drawable.ic_action_aci_stop, "ic_action_aci_stop"));
        add(new Icon(R.drawable.ic_action_aci_stop2, "ic_action_aci_stop2"));
        add(new Icon(R.drawable.ic_action_aci_close, "ic_action_aci_close"));
        add(new Icon(R.drawable.ic_action_aci_close2, "ic_action_aci_close2"));
        add(new Icon(R.drawable.ic_action_aci_caution, "ic_action_aci_caution"));
        add(new Icon(R.drawable.ic_action_aci_arrow_left, "ic_action_aci_arrow_left"));
        add(new Icon(R.drawable.ic_action_aci_arrow_right, "ic_action_aci_arrow_right"));
        add(new Icon(R.drawable.ic_action_aci_arrow_up, "ic_action_aci_arrow_up"));
        add(new Icon(R.drawable.ic_action_aci_arrow_down, "ic_action_aci_arrow_down"));
        add(new Icon(R.drawable.ic_action_aci_arrow2_left, "ic_action_aci_arrow2_left"));
        add(new Icon(R.drawable.ic_action_aci_arrow2_right, "ic_action_aci_arrow2_right"));
        add(new Icon(R.drawable.ic_action_aci_arrow2_up, "ic_action_aci_arrow2_up"));
        add(new Icon(R.drawable.ic_action_aci_arrow2_down, "ic_action_aci_arrow2_down"));
        add(new Icon(R.drawable.ic_action_aci_arrow3_left, "ic_action_aci_arrow3_left"));
        add(new Icon(R.drawable.ic_action_aci_arrow3_right, "ic_action_aci_arrow3_right"));
        add(new Icon(R.drawable.ic_action_aci_arrow3_up, "ic_action_aci_arrow3_up"));
        add(new Icon(R.drawable.ic_action_aci_arrow3_down, "ic_action_aci_arrow3_down"));
        add(new Icon(R.drawable.ic_action_aci_arrow_left_right, "ic_action_aci_arrow_left_right"));
        add(new Icon(R.drawable.ic_action_aci_arrow_up_down, "ic_action_aci_arrow_up_down"));
        add(new Icon(R.drawable.ic_action_aci_fullscreen, "ic_action_aci_fullscreen"));
        add(new Icon(R.drawable.ic_action_aci_normalscreen, "ic_action_aci_normalscreen"));
        add(new Icon(R.drawable.ic_action_aci_change, "ic_action_aci_change"));
        add(new Icon(R.drawable.ic_action_aci_sort, "ic_action_aci_sort"));
        add(new Icon(R.drawable.ic_action_aci_download, "ic_action_aci_download"));
        add(new Icon(R.drawable.ic_action_aci_upload, "ic_action_aci_upload"));
        add(new Icon(R.drawable.ic_action_aci_export, "ic_action_aci_export"));
        add(new Icon(R.drawable.ic_action_aci_import, "ic_action_aci_import"));
        add(new Icon(R.drawable.ic_action_aci_next, "ic_action_aci_next"));
        add(new Icon(R.drawable.ic_action_aci_prev, "ic_action_aci_prev"));
        add(new Icon(R.drawable.ic_action_aci_clock, "ic_action_aci_clock"));
        add(new Icon(R.drawable.ic_action_aci_clock2, "ic_action_aci_clock2"));
        add(new Icon(R.drawable.ic_action_aci_clock3, "ic_action_aci_clock3"));
        add(new Icon(R.drawable.ic_action_aci_history, "ic_action_aci_history"));
        add(new Icon(R.drawable.ic_action_aci_reload, "ic_action_aci_reload"));
        add(new Icon(R.drawable.ic_action_aci_refresh, "ic_action_aci_refresh"));
        add(new Icon(R.drawable.ic_action_aci_undo, "ic_action_aci_undo"));
        add(new Icon(R.drawable.ic_action_aci_redo, "ic_action_aci_redo"));
        add(new Icon(R.drawable.ic_action_aci_document, "ic_action_aci_document"));
        add(new Icon(R.drawable.ic_action_aci_document2, "ic_action_aci_document2"));
        add(new Icon(R.drawable.ic_action_aci_document3, "ic_action_aci_document3"));
        add(new Icon(R.drawable.ic_action_aci_folder, "ic_action_aci_folder"));
        add(new Icon(R.drawable.ic_action_aci_folder2, "ic_action_aci_folder2"));
        add(new Icon(R.drawable.ic_action_aci_folder3, "ic_action_aci_folder3"));
        add(new Icon(R.drawable.ic_action_aci_out, "ic_action_aci_out"));
        add(new Icon(R.drawable.ic_action_aci_in, "ic_action_aci_in"));
        add(new Icon(R.drawable.ic_action_aci_windows, "ic_action_aci_windows"));
        add(new Icon(R.drawable.ic_action_aci_windows2, "ic_action_aci_windows2"));
        add(new Icon(R.drawable.ic_action_aci_cloud, "ic_action_aci_cloud"));
        add(new Icon(R.drawable.ic_action_aci_cloud2, "ic_action_aci_cloud2"));
        add(new Icon(R.drawable.ic_action_aci_cloud4, "ic_action_aci_cloud4"));
        add(new Icon(R.drawable.ic_action_aci_cloud3, "ic_action_aci_cloud3"));
        add(new Icon(R.drawable.ic_action_aci_search, "ic_action_aci_search"));
        add(new Icon(R.drawable.ic_action_aci_zoomin, "ic_action_aci_zoomin"));
        add(new Icon(R.drawable.ic_action_aci_zoomout, "ic_action_aci_zoomout"));
        add(new Icon(R.drawable.ic_action_aci_bookmark, "ic_action_aci_bookmark"));
        add(new Icon(R.drawable.ic_action_aci_bookmark2, "ic_action_aci_bookmark2"));
        add(new Icon(R.drawable.ic_action_aci_flag, "ic_action_aci_flag"));
        add(new Icon(R.drawable.ic_action_aci_star, "ic_action_aci_star"));
        add(new Icon(R.drawable.ic_action_aci_overflow, "ic_action_aci_overflow"));
        add(new Icon(R.drawable.ic_action_aci_share, "ic_action_aci_share"));
        add(new Icon(R.drawable.ic_action_aci_tag, "ic_action_aci_tag"));
        add(new Icon(R.drawable.ic_action_aci_attach, "ic_action_aci_attach"));
        add(new Icon(R.drawable.ic_action_aci_edit, "ic_action_aci_edit"));
        add(new Icon(R.drawable.ic_action_aci_friend, "ic_action_aci_friend"));
        add(new Icon(R.drawable.ic_action_aci_delete, "ic_action_aci_delete"));
        add(new Icon(R.drawable.ic_action_aci_list, "ic_action_aci_list"));
        add(new Icon(R.drawable.ic_action_aci_mail, "ic_action_aci_mail"));
        add(new Icon(R.drawable.ic_action_aci_camera, "ic_action_aci_camera"));
        add(new Icon(R.drawable.ic_action_aci_picture, "ic_action_aci_picture"));
        add(new Icon(R.drawable.ic_action_aci_movie, "ic_action_aci_movie"));
        add(new Icon(R.drawable.ic_action_aci_alarm, "ic_action_aci_alarm"));
        add(new Icon(R.drawable.ic_action_aci_alarm2, "ic_action_aci_alarm2"));
        add(new Icon(R.drawable.ic_action_aci_terminal, "ic_action_aci_terminal"));
    }

}
